from colorama import Fore, Back, Style

# Define the color constants
ERROR_CONSOLE_BOLD_TEXT = Fore.RED + Style.BRIGHT
ERROR_CONSOLE_TEXT = Fore.RED + Style.NORMAL
SUCCESS_CONSOLE_BOLD_TEXT = Fore.GREEN + Style.BRIGHT
SUCCESS_CONSOLE_TEXT = Fore.GREEN + Style.NORMAL
INFO_CONSOLE_BOLD_TEXT = Fore.YELLOW + Style.BRIGHT
INFO_CONSOLE_TEXT = Fore.YELLOW + Style.NORMAL
LOG_CONSOLE_TEXT = Fore.BLUE + Style.NORMAL
LOG_CONSOLE_BOLD_TEXT = Fore.BLUE + Style.BRIGHT
TEXT_BOLD_HIGHTLITED = Fore.WHITE + Style.BRIGHT
BOLD_CONSOLE_TEXT = Style.BRIGHT
BK_BLUE_WHITE_TEXT = Fore.WHITE + Back.BLUE + Style.BRIGHT
BK_WHITE_BLUE_TEXT = Fore.BLUE + Back.WHITE + Style.BRIGHT
BK_RED_WHITE_TEXT = Fore.WHITE + Back.RED + Style.BRIGHT
NORMAL_CONSOLE_TEXT = Style.RESET_ALL


